use std::fs::File;
use std::io::Write;
use std::path::Path;

fn main() {
    let out_dir = String::from("./");
    let dest_path = Path::new(&out_dir).join("./src/hello.rs");
    let mut f = File::create(&dest_path).unwrap();

    f.write_all(
        b"
pub fn message() -> &'static str {
    \"Hello, World, this is generated by build.rs!\"
}",
    )
    .unwrap();

    println!("build finished.");
}
